# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Npm@1
  inputs:
    command: 'install'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export GITHUB_ACCESS_TOKEN=$(Github-PAT-Carthage)
      carthage bootstrap --platform iOS --cache-builds && echo '*** Resolved dependencies:' && cat 'Cartfile.resolved'  

- task: CocoaPods@0
  inputs:
    forceRepoUpdate: false

- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Debug'
    sdk: 'iphoneos'
    xcWorkspacePath: '**/AdaptiveCardSwiftSample.xcworkspace'
    packageApp: false

- task: WhiteSource Bolt@20
  inputs:
    cwd: '${Build.SourcesDirectory}'
